### PR TITLE
Added OG image, style & tab behavior fixes

### PR DESCRIPTION
**Pull request by alanvww**
## Style
 - Hide banner in mobile view
 - Make title text overflow into new line if it is too long
 - Tried to move the sidebar over the banner when it is opened to ensure mobile experience, but failed :(

## Tab (ml5 glossary)
Added logic to fix behavior. Now if the link is internal, the tab will force reload to make sure the content is correct.

### CODE REVIEW

**Comment by alanvww** [comment]
Open Graph image preview:
CleanShot 2024-08-02 at 17 27 37@2x

CleanShot 2024-08-02 at 17 29 00@2x

**Comment by shiffman** [comment]
For the future, it might be fun to make an image that includes the illustrations from the homepage around the ml5.js logo?

**Comment by alanvww** [comment]
> For the future, it might be fun to make an image that includes the illustrations from the homepage around the ml5.js logo?

Thanks Dan! I love this idea. I will start making a few options and put them in an new issue so we can discuss and pick one 😃

**Comment by MOQN** [comment]
@shiffman thank you for sharing the idea! That sounds great!

@alanvww Pacey and I already prepared a B&W version of all the drawing images. I believe they should be useful for the current OG image draft.

**Comment by MOQN** [comment]
@alanvww thank you so much! I am merging the current one. Let's discuss the further enhancement shortly.

**Pull request merged**
