### PR TITLE
Quinn rewrite bodypose content

### PR DESCRIPTION
**Pull request by QuinnHe**
To-do
1. think about the order of `examples` vs `How to`
2. a bit more detailed work on `methods`
3. review the whole session wording again

### CODE REVIEW

**Comment by QuinnHe** [comment]
Suggestion from Myrah:
1. remove link of demo, how to
2. use consistent file names, i.e, "index.html"
3. combine "demo" with "quick start"
4. rename "how to" to "tutroial"

**Comment by alanvww** [comment]
Hello Quinn! I just went over the to-do list that Moon shared with me. 

In terms of the incorrect methods of BodyPose, would you please elaborate it a little bit more? I just double check the code of the library and also the example code snippet, I think the content on the preview deployment above is pretty much correct. [Here is the p5 sketch I made. ](https://editor.p5js.org/alanvww/sketches/DR3Od7rN1) 

I think the explanation of this function will also be great to display with these two pictures of keypoints: 
CleanShot 2024-06-12 at 00 07 53@2x

**Comment by alanvww** [comment]
And for the "Single Image", I think the main difference is the way to call the detect method.
```javascript
  /**
   * Asynchronously outputs a single pose prediction result when called.
   * @param {*} media - An HMTL or p5.js image, video, or canvas element to run the prediction on.
   * @param {gotPoses} callback - A callback function to handle the predictions.
   * @returns {Promise<Array>} an array of poses.
   */
  async detect(...inputs) {
  }

  /**
   * Repeatedly outputs pose predictions through a callback function.
   * Calls the internal detectLoop() function.
   * @param {*} media - An HMTL or p5.js image, video, or canvas element to run the prediction on.
   * @param {gotPoses} callback - A callback function to handle the predictions.
   * @returns {Promise<Array>} an array of predictions.
   */
  detectStart(...inputs) {
  }
```
For `detect()`, it will only run once, so it will be the great way to go with single image detection.

**Comment by QuinnHe** [comment]
Hey @alanvww , thanks for the updates! What I mean by missing method is focus on “Methods” this section, not “How To”. So in “Methods”, for now we just copy paste from Peter’s documentation.md and we may miss some methods like “getSkeleton”. I explained getSkeleton in the “How To” because we used it in the example code.

**Comment by alanvww** [comment]
> Hey @alanvww , thanks for the updates! What I mean by missing method is focus on “Methods” this section, not “How To”. So in “Methods”, for now we just copy paste from Peter’s documentation.md and we may miss some methods like “getSkeleton”. I explained getSkeleton in the “How To” because we used it in the example code.

Got it! I will keep that in mind. For the "single image" and "detectStart / End methods", do we need both code examples and descriptions, or just one of them? If you and Myrah already have content on them, I can add on to it.

**Comment by QuinnHe** [comment]
> > Hey @alanvww , thanks for the updates! What I mean by missing method is focus on “Methods” this section, not “How To”. So in “Methods”, for now we just copy paste from Peter’s documentation.md and we may miss some methods like “getSkeleton”. I explained getSkeleton in the “How To” because we used it in the example code.
> 
> Got it! I will keep that in mind. For the "single image" and "detectStart / End methods", do we need both code examples and descriptions, or just one of them? If you and Myrah already have content on them, I can add on to it.

Description is required and example code is good to have. You can use any library documentation as a reference, where each method will have its description, explanation on each parameters, return vars, and default/available values for each parameter, and even example code snippet on how to use the method.

**Comment by MOQN** [comment]
Thank you for the amazing updates!

**Pull request merged**
