### PR TITLE
[WIP] Documentation Edits

### PR DESCRIPTION
**Pull request by shiffman**
I'm starting to  go through and edit the documentation pages. 

I wonder if the the explanation of how to run the ml5.js sketch "locally" is adding too much noise to the getting started page. it doesn't feel so simple. I might prefer to bury a page around how to work with ml5.js outside of the p5.js web editor somewhere else (or not include it at all.)

This might also leave some space for thinking about whether "Getting Started" should include, say, `handPose()` in addition to or instead of `imageClassifier()`?

What do you all think?

### CODE REVIEW

**Comment by shiffman** [comment]
I've done a brief pass over the BodyPose docs, I think it might make sense for me to pause here and discuss some notes and thoughts around the documentation language before editing other pages.

1. I adjusted some language that felt like it had an overly "sales"-like tone. I think it's best for us to avoid language that suggests that the model is "high accuracy" or "great for fitness apps"! It's better to be more cautious around the limitations of ML models and their applications, as well as let the reader make their own judgements.
2. I linked to MoveNet and BlazePose documentation, but I think we could do more to provide resources and learning materials for the genesis of the models.
3. I would focus on highlighting links to the web editor examples which is what I expect visitors will do (rather than copy/paste and create new examples for themselves.) 
4. The documentation could use perhaps additional explanation around how the results are stored, and now to access individual body parts vs. iterate over all keypoints. But this is more likely the domain of a tutorial, which I'll be excited to tackle in the future!

**Comment by QuinnHe** [comment]
> I'm starting to go through and edit the documentation pages.
> 
> I wonder if the the explanation of how to run the ml5.js sketch "locally" is adding too much noise to the getting started page. it doesn't feel so simple. I might prefer to bury a page around how to work with ml5.js outside of the p5.js web editor somewhere else (or not include it at all.)
> 
> This might also leave some space for thinking about whether "Getting Started" should include, say, `handPose()` in addition to or instead of `imageClassifier()`?
> 
> What do you all think?

Thanks, Dan!! 

 _I wonder if the the explanation of how to run the ml5.js sketch "locally" is adding too much noise to the getting started page. it doesn't feel so simple. I might prefer to bury a page around how to work with ml5.js outside of the p5.js web editor somewhere else (or not include it at all.)_
Agree with the idea of separating out "run ml5 locally". 
Several options that come to mind about where to put this page:
1. Make "run ml5 with a local web server" as one of the sections on the "Next Steps" page, and make it sound like one step further than only launching at p5 web editor. Something like "Would like to use ml5 outside p5 editor, and even build a website out of it? Follow our tutorial here". Then we add "ml5 tutorial" under "Learning" section, and include "How to run ml5 with a local web server"  as one of the tutorials, along with other tutorials contributed by our community and users.
2. We include "Can I run ml5 with a local server?" in FAQ. And then we link to "Learning"/"ml5 tutorial"/"How to run ml5 with a local web server"
3. We add a lightbulb tip at the very beginning of the Getting Started page and say "If you would like to run ml5 outside p5 web editor, check out our tutorial". And then link to "Learning"/"ml5 tutorial"/"How to run ml5 with a local web server".

_This might also leave some space for thinking about whether "Getting Started" should include, say, `handPose()` in addition to or instead of `imageClassifier()`?_
I definitely feel only including one model in the getting started page is better than using two models. In terms of choosing one of them as the model in user's first sketch, I don't have a strong preference. I feel handpose is definitely more interesting and more ml5 style compared to imageClassifier, while imageClassifier's result is more straightforward to understand (a label and confidence, and that's it). @MOQN Maybe Moon you have more thoughts on this :)

**Comment by shiffman** [comment]
Hi @QuinnHe and @myrahsa, sorry I left this branch + pull request dangling in the repo. I've been watching all the edits come in and the new website is coming along beautifully! I could go through this again and resolve conflicts, but perhaps it makes sense to close this branch. It can exist as comments and ideas that you can incorporate separately as you are doing yoru edits (many of which I think you already have.)

Let me know what you think!

**Comment by QuinnHe** [comment]
> Hi @QuinnHe and @myrahsa, sorry I left this branch + pull request dangling in the repo. I've been watching all the edits come in and the new website is coming along beautifully! I could go through this again and resolve conflicts, but perhaps it makes sense to close this branch. It can exist as comments and ideas that you can incorporate separately as you are doing yoru edits (many of which I think you already have.)
> 
> Let me know what you think!

Thanks Dan @shiffman ! Since we are rewriting the getting started page and bodyPose pages with great portion completely different from previous version, maybe we can consider close the PR and use Dan your comments & commits as reference? We will go through each line of your commits and make sure we incorporate the changes that haven't been taken care so far. The two things we haven't included, and we will definitely go back to this PR to double check:
1. Dan your changes on bodyPose example code comments
2. Dan your changes on bodyPose methods

cc @MOQN @myrahsa

**Comment by MOQN** [comment]
> This might also leave some space for thinking about whether "Getting Started" should include, say, `handPose()` in addition to or instead of `imageClassifier()`?_

I still believe including `handPose()` is beneficial. We will see if we can implement it this week or after the soft launch.

**Comment by MOQN** [comment]
> I would focus on highlighting links to the web editor examples which is what I expect visitors will do (rather than copy/paste and create new examples for themselves.)

@QuinnHe reminded us of this point. We will revise the structure, highlighting example codes that are linked to the p5.js web editor.

> The documentation could use perhaps additional explanation around how the results are stored, and now to access individual body parts vs. iterate over all keypoints. But this is more likely the domain of a tutorial, which I'll be excited to tackle in the future!

We will definitely work on them!

**Comment by shiffman** [comment]
Thank you everyone, this all makes sense to me! Feel free to use anything from my edits in new branches / drafts and close this PR whenever there is nothing left relevant!

**Comment by shiffman** [comment]
Hi @myrahsa I think this can be closed now that you pulled any relevant changes from here into your branch? Let me know!

**Pull request closed without merging**
