### PR TITLE
Changed `flipHorizontal` to `flipped`

### PR DESCRIPTION
**Pull request by alanvww**
@MOQN @QuinnHe Fixed the options: Changed `flipHorizontal` to `flipped` to match p5.

@ziyuan-linn I noticed that `flipped` is also in `BodySegmentation` and `BodyPose`, but didn't mention it in the comments and examples. Is it a valid option so we can include it in the docs?

### CODE REVIEW

**Comment by ziyuan-linn** [comment]
Hi @alanvww! the `flipped` property is valid on `BodySegmentation`, `BodyPose`, `HandPose`, and `FaceMesh`. The comments probably need some cleanup and updating. Also `flipped` is technically implemented as an alias of `flipHorizontal`, so the `flipHorizontal` property still works for any model with the `flipped` property. Though it's probably not relevant for the docs.

**Comment by alanvww** [comment]
> Hi @alanvww! the `flipped` property is valid on `BodySegmentation`, `BodyPose`, `HandPose`, and `FaceMesh`. The comments probably need some cleanup and updating. Also `flipped` is technically implemented as an alias of `flipHorizontal`, so the `flipHorizontal` property still works for any model with the `flipped` property. Though it's probably not relevant for the docs.

Got it. I know it works as an alias and they're the same. Dan mentioned it during the launch, so if we want to align with how p5 named it, we should change it :)

**Comment by alanvww** [comment]
@QuinnHe https://github.com/ml5js/ml5-next-gen/issues/106 with the example in this PR, p5 now support 
```
video = createCapture(VIDEO, { flipped: true });
```
and I think it is great to include both names but looks like `flipped` is the one that should be highlighted.

**Comment by QuinnHe** [comment]
> @QuinnHe [ml5js/ml5-next-gen#106](https://github.com/ml5js/ml5-next-gen/issues/106) with the example in this PR, p5 now support
> 
> ```
> video = createCapture(VIDEO, { flipped: true });
> ```
> 
> and I think it is great to include both names but looks like `flipped` is the one that should be highlighted.

Thanks @alanvww ! Yes, your points make sense! Okie, let's follow what you suggest here, and maybe include them into BodySegmentation and BodyPose?

**Comment by alanvww** [comment]
> > @QuinnHe [ml5js/ml5-next-gen#106](https://github.com/ml5js/ml5-next-gen/issues/106) with the example in this PR, p5 now support
> 
> > 
> 
> > ```
> 
> > video = createCapture(VIDEO, { flipped: true });
> 
> > ```
> 
> > 
> 
> > and I think it is great to include both names but looks like `flipped` is the one that should be highlighted.
> 
> 
> 
> Thanks @alanvww ! Yes, your points make sense! Okie, let's follow what you suggest here, and maybe include them into BodySegmentation and BodyPose?

I will add more commit for BodySegmentation and BodyPose later :D

**Comment by shiffman** [comment]
Thank you for working on this @alanvww! I think it probably makes sense for *all* of the examples to include `flipped: true` by default since this is the most common, expected behavior!

**Comment by MOQN** [comment]
@alanvww Thank you for taking care of all of these things!

**Pull request merged**
