### PR TITLE
Some suggestions for Getting Started

### PR DESCRIPTION
**Pull request by gohai**
Here some suggestions for reading through the Getting Started - please take the parts you find helpful, and ignore the rest!

### CODE REVIEW

**Comment by gohai** [comment]
tagging @QuinnHe :)

**Comment by QuinnHe** [comment]
Thank you @gohai!! This is super helpful, will merge it to the main today :)

**Comment by shiffman** [comment]
I deployed the repo to netlify and configured preview builds, you can now see your updates @gohai here!

https://deploy-preview-48--ml5-next-gen-docs.netlify.app/#/

I had to commit something to trigger the rebuild so I lowercased `ml5` whichi is the preferred style :)

**Comment by MOQN** [comment]
@gohai, thank you for all the suggestions. Super helpful!

@shiffman, thank you for the modification! We noted the preferred style during the meeting, and we will make sure to keep consistency by changing the rest to lowercase.

**Pull request merged**
